### PR TITLE
clearer error messages on app.py; added more tests

### PR DESCRIPTION
**Pull request by darensin01**
Changes made:

- Added clearer error messages on `app.py` that helps the user figure out what is wrong with their request (happened to me while using the app for the first time)
- Instead of checking if the pattern `is_valid()`, I split the test into 2 parts: checking for valid acceptable category length, and checking if all the categories entered exist
- Added more tests to `test_pattern.py`. In particular, I noticed that there's no test for the case where `pattern=''` (empty string)

### CODE REVIEW

**Review by gabrielbarker — APPROVED** [review]
Great work, this will be really useful, thank you

**Comment by gabrielbarker** [comment]
Thanks a lot @darensin01 !

**Comment by gabrielbarker** [comment]
#24

**Comment by darensin01** [comment]
Thanks @gabrielbarker! :)

**Pull request merged**
