### PR TITLE
Add new category tool, written test class, added to __category_map

### PR DESCRIPTION
**Pull request by Vivek-blip**

### CODE REVIEW

**Review by gabrielbarker — APPROVED** [review]
Nailed it first try @Vivek-blip

**Comment by gabrielbarker** [comment]
Thanks so much for your contribution! 🎉

**Comment by Vivek-blip** [comment]
Enjoyed my first OS contribution 😁

**Comment by gabrielbarker** [comment]
Good for you man! It's not easy to get a PR merged with no comments, well done!

**Comment by Vivek-blip** [comment]
> Good for you man! It's not easy to get a PR merged with no comments, well done!

Thanks man😊

**Pull request merged**
