### PR TITLE
Added capital category and corrected existing file formatting

### PR DESCRIPTION
**Pull request by digitalvirtuoso**
Corrected formatting in anime.py
Added capital.py for capital cities around the world. #42 
Added the new category into pattern.py
Added test_capital.py

### CODE REVIEW

**Review by gabrielbarker — CHANGES_REQUESTED** [review]
Hey @digitalvirtuoso thanks a lot for the contribution. This has happened a few times (maybe I should make the docs a bit clearer), but when I say in CONTRIBUTING.md that spaces and special chars are not allowed, I mean that values should ideally be single words. A few of these capitals (though seemingly not many), are multiple words, `bandarseribegawan` for example. Would you be up for removing these entries? let me know your thoughts
Thanks again! 🙂

**Comment by digitalvirtuoso** [comment]
@gabrielbarker Sure, I didn't see in the docs that it could not be multiple words.  I can do a quick go back and remove the capitals that are combinations of words.  If you don't mind tagging this PR hacktoberfest-accepted, I'd appreciate that! :)

**Comment by gabrielbarker** [comment]
Great! Thanks @digitalvirtuoso ! I think this PR should count anyway as the repo is tagged by I'll add the tag just to be sure

**Comment by digitalvirtuoso** [comment]
Updated requested changes!  I appreciate the tag!

**Review by gabrielbarker — APPROVED** [review]
Perfect, thanks

**Comment by gabrielbarker** [comment]
This looks great now @digitalvirtuoso , thanks so much for the contribution! 🎉

**Pull request merged**
