### PR TITLE
Added a new Cuisine category

### PR DESCRIPTION
**Pull request by PravunathSingh**
For issue number #42

### CODE REVIEW

**Comment by PravunathSingh** [comment]
Hey @gabrielbarker I have made a PR for the new Cuisine category which I have added, but there's a conflict with qual_id/pattern.py. This didn't happen earlier when I added the festivals category. 

It would be great if you could provide some insights regarding this.

**Comment by gabrielbarker** [comment]
Hey @PravunathSingh , conflicts happen all the time, they're annoying but just part of git. The reason they've happened here is, on the main branch, the category currency exists, and on your branch it doesn't _and cuisine does_. They're next to each other alphabetically so git doesn't know which change we want. In this case, we want both. There are lots of ways to fix this, but in this case I would recommend clicking the `Resolve conflicts` button and keeping the lines for cuisine and for currency, removing the text that's like `<<<<<< category-cusine` etc.

Bear in mind that you will need to switch the order that they appear so they are alphabetical!

Then once you're done, just hit the button at the bottom that says `commit` or something. Let me know if you get stuck, and if it all goes wrong then I'll be able to sort it out (hopefully haha) so don't worry about messing anything up 🙂

**Comment by PravunathSingh** [comment]
Hey @gabrielbarker thanks for the help!! The conflict is resolved now. You can review the PR now and let me know if everything's good to go!

**Review by gabrielbarker — APPROVED** [review]
Perfect!

**Comment by gabrielbarker** [comment]
Well done @PravunathSingh ! You resolved the conflicts perfectly! Thanks for the contribution 🎉

**Comment by PravunathSingh** [comment]
I'm glad I am able to contribute to this project. Thanks for all the help and suggestions @gabrielbarker

**Pull request merged**
