### PR TITLE
Added anime category class

### PR DESCRIPTION
**Pull request by gremlin97**
This contributes to #42

### CODE REVIEW

**Comment by gabrielbarker** [comment]
Hey @gremlin97 , thanks for sorting out those failing tests. I've mentioned this to other people who've contributed, but in CONTRIBUTING.md, where I've requested that spaces and special characters not be included, what I mean is that I would like values to be _single words_. Some of your contributions here are clearly fine, like 'naruto', but others that are just multiple words combined are not. Would you be able to still add this category, but only use single words? Let me know your thoughts 🙂

**Comment by gremlin97** [comment]
Yeah Sure :smiley: . Now that I think about it having complex concatenated strings definitely beats the purpose of qual-id :sweat_smile: .

**Review by gremlin97 — COMMENTED** [review]
Removed concatenated anime titles.

**Review by gabrielbarker — APPROVED** [review]
Thanks for taking my comments on board!

**Comment by gabrielbarker** [comment]
Great contribution @gremlin97 ! Thanks a lot! 🎉  🙂

**Comment by gremlin97** [comment]
Thanks for the help :tada:.  Looking forward to contribute in the future :smile:.

**Pull request merged**
