### PR TITLE
 Issue #42, Added new category Currency

### PR DESCRIPTION
**Pull request by devanaggarwal**

### CODE REVIEW

**Comment by gabrielbarker** [comment]
Hey @devanaggarwal , I really like this idea for a category but I was expecting it to be like
- dollar
- pound
- euro
- bolivar
- peso
- rupee
...
etc.
I'm not sure the three letter codes will be as effective. I'm imagining using currency with another category, to form an id, I think 'dollar-penguin' will be a lot better and more memorable than 'czk-penguin'. Let me know what you think about this suggestion 🙂

**Comment by devanaggarwal** [comment]
Sounds better, I will make the changes.

**Comment by devanaggarwal** [comment]
hey @gabrielbarker, please review the changes.

**Review by gabrielbarker — APPROVED** [review]
This looks perfect now, thanks @devanaggarwal

**Comment by gabrielbarker** [comment]
Thanks for the contribution and thanks so much for making those changes @devanaggarwal ! 🎉 🙂

**Pull request merged**
