### PR TITLE
Add new category for bird

### PR DESCRIPTION
**Pull request by jaqsparow**
Adding new category for bird :)

### CODE REVIEW

**Review by gabrielbarker — APPROVED** [review]
Looks perfect to me!

**Comment by gabrielbarker** [comment]
Thanks again @jaqsparow , fantastic contribution 🙂

**Comment by jaqsparow** [comment]
👍🏻

**Comment by jaqsparow** [comment]
Just checking. Did you push the changes to heroku? I still see 'bird' as invalid category

**Comment by gabrielbarker** [comment]
Thanks for bringing this to my attention, apparently the deploy failed. All good now though! [As you can see](https://qual-id.herokuapp.com/get/?pattern=fruit-bird)

**Comment by jaqsparow** [comment]
Looks good now :)

**Pull request merged**
